# ETAPA 1: Construcción (Node)
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# NUEVA LÍNEA CLAVE: Declarar argumentos para que Vite los capture en el build
ARG VITE_API_URL_VENTAS
ARG VITE_API_URL_DESPACHOS
ENV VITE_API_URL_VENTAS=$VITE_API_URL_VENTAS
ENV VITE_API_URL_DESPACHOS=$VITE_API_URL_DESPACHOS

RUN npm run build

# ETAPA 2: Servidor Web (Nginx)
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid /var/cache/nginx /var/log/nginx /usr/share/nginx/html

USER nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]