version: '3.8'

services:
  back-ventas:
    build: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: app-back-ventas-1
    ports:
      - "8081:8081" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://10.0.3.45:3306/grupo_cordillera_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always

  back-despacho:
    build: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: app-back-despacho-1
    ports:
      - "8082:8081" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://10.0.3.45:3306/grupo_cordillera_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always