version: '3.8'

services:
  app-frontend:
    build:
      context: ./front_despacho
      dockerfile: Dockerfile
      args:
        - VITE_API_URL_VENTAS=${VITE_API_URL_VENTAS}
        - VITE_API_URL_DESPACHOS=${VITE_API_URL_DESPACHOS}
    container_name: app-front-ventas
    ports:
      - "8085:80"
    restart: always

    #va