apiVersion: apps/v1
kind: Deployment

metadata:

  name: backend-ventas
  namespace: tienda


spec:

  replicas: 1


  selector:

    matchLabels:

      app: backend-ventas


  template:

    metadata:

      labels:

        app: backend-ventas


    spec:


      containers:


      - name: backend-ventas


        image: 317239159781.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:latest


        ports:


        - containerPort: 8081



        env:


        - name: SPRING_DATASOURCE_URL

          value: jdbc:mysql://mysql:3306/grupo_cordillera_db?useSSL=false&serverTimezone=UTC



        - name: SPRING_DATASOURCE_USERNAME

          value: root



        - name: SPRING_DATASOURCE_PASSWORD

          value: root



---


apiVersion: apps/v1
kind: Deployment


metadata:

  name: backend-despacho
  namespace: tienda



spec:


  replicas: 1



  selector:


    matchLabels:


      app: backend-despacho



  template:


    metadata:


      labels:


        app: backend-despacho



    spec:


      containers:



      - name: backend-despacho



        image: 317239159781.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:latest



        ports:



        - containerPort: 8082



        env:



        - name: SPRING_DATASOURCE_URL


          value: jdbc:mysql://mysql:3306/grupo_cordillera_db?useSSL=false&serverTimezone=UTC



        - name: SPRING_DATASOURCE_USERNAME


          value: root



        - name: SPRING_DATASOURCE_PASSWORD


          value: root