apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tienda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 466563729620.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80