name: Deploy Application to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Frontend image
        run: docker build -t tienda-frontend ./front_despacho

      - name: Push Frontend image
        run: |
          docker tag tienda-frontend:latest ${{ secrets.ECR_FRONTEND }}:latest
          docker push ${{ secrets.ECR_FRONTEND }}:latest

      - name: Build Backend image
        run: docker build -t tienda-backend ./back-Ventas_SpringBoot/Springboot-API-REST

      - name: Push Backend image
        run: |
          docker tag tienda-backend:latest ${{ secrets.ECR_BACKEND }}:latest
          docker push ${{ secrets.ECR_BACKEND }}:latest

      - name: Configure kubectl
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Verify EKS Connection
        run: kubectl get nodes

      - name: Debug Files
        run: |
          pwd
          ls -R
          echo "===== namespace.yaml ====="
          cat k8s/namespace.yaml

      - name: Deploy Kubernetes manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/ -n ${{ secrets.EKS_NAMESPACE }}
          
          # ---> AQUÍ VAN LOS COMANDOS DE ACTUALIZACIÓN <---
          kubectl rollout restart deployment frontend -n ${{ secrets.EKS_NAMESPACE }}
          kubectl rollout restart deployment backend-despacho -n ${{ secrets.EKS_NAMESPACE }}

      - name: Verify Deployment
        run: |
          kubectl get pods -n ${{ secrets.EKS_NAMESPACE }}
          kubectl get svc -n ${{ secrets.EKS_NAMESPACE }}
          kubectl get deployments -n ${{ secrets.EKS_NAMESPACE }}